version: '3'

services:
  website:
    build: .
    command: >
      gunicorn -c "python:config.gunicorn" --reload "tracker.app:create_app()"
    links:
      - memcached:memcached
    env_file:
      - '.env'
    volumes:
      - '.:/app'
    ports:
      - '5000:5000'

  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"