version: '3'

services:
  web:
    build: .
    env_file: .env
    volumes:
      - "./app:/app"
    command:  sh -c "gunicorn -c 'python:config.gunicorn' --reload 'tracker.app:create_app()'"
    ports:
      - '9000:5000'
